/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppVoiceRouteImport } from './routes/_authenticated.app.voice'
import { Route as AuthenticatedAppSavedRouteImport } from './routes/_authenticated.app.saved'
import { Route as AuthenticatedAppJobsRouteImport } from './routes/_authenticated.app.jobs'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated.app.history'
import { Route as AuthenticatedAppCvRouteImport } from './routes/_authenticated.app.cv'
import { Route as AuthenticatedAppJobsJobIdRouteImport } from './routes/_authenticated.app.jobs.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppVoiceRoute = AuthenticatedAppVoiceRouteImport.update({
  id: '/app/voice',
  path: '/app/voice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSavedRoute = AuthenticatedAppSavedRouteImport.update({
  id: '/app/saved',
  path: '/app/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppJobsRoute = AuthenticatedAppJobsRouteImport.update({
  id: '/app/jobs',
  path: '/app/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCvRoute = AuthenticatedAppCvRouteImport.update({
  id: '/app/cv',
  path: '/app/cv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppJobsJobIdRoute =
  AuthenticatedAppJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedAppJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cv': typeof AuthenticatedAppCvRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/jobs': typeof AuthenticatedAppJobsRouteWithChildren
  '/app/saved': typeof AuthenticatedAppSavedRoute
  '/app/voice': typeof AuthenticatedAppVoiceRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cv': typeof AuthenticatedAppCvRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/jobs': typeof AuthenticatedAppJobsRouteWithChildren
  '/app/saved': typeof AuthenticatedAppSavedRoute
  '/app/voice': typeof AuthenticatedAppVoiceRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/cv': typeof AuthenticatedAppCvRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/jobs': typeof AuthenticatedAppJobsRouteWithChildren
  '/_authenticated/app/saved': typeof AuthenticatedAppSavedRoute
  '/_authenticated/app/voice': typeof AuthenticatedAppVoiceRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/jobs/$jobId': typeof AuthenticatedAppJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/cv'
    | '/app/history'
    | '/app/jobs'
    | '/app/saved'
    | '/app/voice'
    | '/app/'
    | '/app/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cv'
    | '/app/history'
    | '/app/jobs'
    | '/app/saved'
    | '/app/voice'
    | '/app'
    | '/app/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/cv'
    | '/_authenticated/app/history'
    | '/_authenticated/app/jobs'
    | '/_authenticated/app/saved'
    | '/_authenticated/app/voice'
    | '/_authenticated/app/'
    | '/_authenticated/app/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/voice': {
      id: '/_authenticated/app/voice'
      path: '/app/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AuthenticatedAppVoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/saved': {
      id: '/_authenticated/app/saved'
      path: '/app/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AuthenticatedAppSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/jobs': {
      id: '/_authenticated/app/jobs'
      path: '/app/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AuthenticatedAppJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/cv': {
      id: '/_authenticated/app/cv'
      path: '/app/cv'
      fullPath: '/app/cv'
      preLoaderRoute: typeof AuthenticatedAppCvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/jobs/$jobId': {
      id: '/_authenticated/app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppJobsRoute
    }
  }
}

interface AuthenticatedAppJobsRouteChildren {
  AuthenticatedAppJobsJobIdRoute: typeof AuthenticatedAppJobsJobIdRoute
}

const AuthenticatedAppJobsRouteChildren: AuthenticatedAppJobsRouteChildren = {
  AuthenticatedAppJobsJobIdRoute: AuthenticatedAppJobsJobIdRoute,
}

const AuthenticatedAppJobsRouteWithChildren =
  AuthenticatedAppJobsRoute._addFileChildren(AuthenticatedAppJobsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppCvRoute: typeof AuthenticatedAppCvRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppJobsRoute: typeof AuthenticatedAppJobsRouteWithChildren
  AuthenticatedAppSavedRoute: typeof AuthenticatedAppSavedRoute
  AuthenticatedAppVoiceRoute: typeof AuthenticatedAppVoiceRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppCvRoute: AuthenticatedAppCvRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppJobsRoute: AuthenticatedAppJobsRouteWithChildren,
  AuthenticatedAppSavedRoute: AuthenticatedAppSavedRoute,
  AuthenticatedAppVoiceRoute: AuthenticatedAppVoiceRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
