/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppVoiceRouteImport } from './routes/_authenticated.app.voice'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated.app.history'
import { Route as AuthenticatedAppGenerateRouteImport } from './routes/_authenticated.app.generate'
import { Route as AuthenticatedAppCvRouteImport } from './routes/_authenticated.app.cv'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppVoiceRoute = AuthenticatedAppVoiceRouteImport.update({
  id: '/app/voice',
  path: '/app/voice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppGenerateRoute =
  AuthenticatedAppGenerateRouteImport.update({
    id: '/app/generate',
    path: '/app/generate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCvRoute = AuthenticatedAppCvRouteImport.update({
  id: '/app/cv',
  path: '/app/cv',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cv': typeof AuthenticatedAppCvRoute
  '/app/generate': typeof AuthenticatedAppGenerateRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/voice': typeof AuthenticatedAppVoiceRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cv': typeof AuthenticatedAppCvRoute
  '/app/generate': typeof AuthenticatedAppGenerateRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/voice': typeof AuthenticatedAppVoiceRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/cv': typeof AuthenticatedAppCvRoute
  '/_authenticated/app/generate': typeof AuthenticatedAppGenerateRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/voice': typeof AuthenticatedAppVoiceRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/cv'
    | '/app/generate'
    | '/app/history'
    | '/app/voice'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cv'
    | '/app/generate'
    | '/app/history'
    | '/app/voice'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/cv'
    | '/_authenticated/app/generate'
    | '/_authenticated/app/history'
    | '/_authenticated/app/voice'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/voice': {
      id: '/_authenticated/app/voice'
      path: '/app/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AuthenticatedAppVoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/generate': {
      id: '/_authenticated/app/generate'
      path: '/app/generate'
      fullPath: '/app/generate'
      preLoaderRoute: typeof AuthenticatedAppGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/cv': {
      id: '/_authenticated/app/cv'
      path: '/app/cv'
      fullPath: '/app/cv'
      preLoaderRoute: typeof AuthenticatedAppCvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppCvRoute: typeof AuthenticatedAppCvRoute
  AuthenticatedAppGenerateRoute: typeof AuthenticatedAppGenerateRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppVoiceRoute: typeof AuthenticatedAppVoiceRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppCvRoute: AuthenticatedAppCvRoute,
  AuthenticatedAppGenerateRoute: AuthenticatedAppGenerateRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppVoiceRoute: AuthenticatedAppVoiceRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
