// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { cleanEnvValue, getBrowserRuntimeEnv } from '@/lib/public-env';

function createSupabaseClient() {
  const runtimeEnv = getBrowserRuntimeEnv();

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to SSR-injected runtime env and then process.env for server rendering.
  const SUPABASE_URL =
    cleanEnvValue(import.meta.env.VITE_SUPABASE_URL) ||
    cleanEnvValue(runtimeEnv?.SUPABASE_URL) ||
    (typeof window === "undefined"
      ? cleanEnvValue(process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL)
      : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    cleanEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    cleanEnvValue(runtimeEnv?.SUPABASE_PUBLISHABLE_KEY) ||
    (typeof window === "undefined"
      ? cleanEnvValue(process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY)
      : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const hint =
      typeof window === "undefined"
        ? "Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in the server environment."
        : "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your frontend deployment environment (Production scope) and redeploy.";
    throw new Error(
      `Missing Supabase environment variables. ${hint}`
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

